[package]
name = "web_server_demo"
version = "0.1.0"
authors = ["ethanzhang"]
edition = "2018"

[dependencies]
actix-web = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.1"
